services:
  regnav-vector-db:
    image: qdrant/qdrant:dev
    container_name: regnav-vector-db
    ports:
      - 6333:6333
    volumes:
      - vector-db-data:/qdrant/storage

volumes:
  vector-db-data:
